spec:
  projectName: gitops-repo
  releaseName: metallb
  namespace: metallb
  addressPool: '10.4.11.0 - 10.4.15.254'
  source:
    repoURL: 'https://metallb.github.io/metallb'
    chart: 'metallb'
    targetRevision: '0.14.5'
    helm:
      releaseName: 'metallb'
      version: v3
