projectName: gitops-repo
releaseName: metallb
namespace: metallb
peerName: marbrand
myASN: 64501
peerASN: 64500
peerAddress: 10.4.0.1
addresses:
  - 10.4.11.0 - 10.4.15.254
source:
  repoURL: 'https://metallb.github.io/metallb'
  chart: 'metallb'
  targetRevision: '0.14.3'
  helm:
    releaseName: 'metallb'
