apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.spec.releaseName }}"
  namespace: argocd
  labels:
    name: "{{ .Values.spec.releaseName }}"
    managed-by: 'argocd'
  annotations:
    argocd.argoproj.io/wave: '-4'
spec:
  project: "{{ .Values.spec.projectName }}"
  source:
    repoURL: "{{ .Values.spec.source.repoURL }}"
    chart: "{{ .Values.spec.source.chart }}"
    targetRevision: "{{ .Values.spec.source.targetRevision }}"
    helm:
      releaseName: "{{ .Values.spec.releaseName }}"
      valuesObject:
        rbac:
          create: true
        prometheus:
          scrapeAnnotations: true
          metricsPort: 7472
          rbacPrometheus: true
        speaker:
          frr:
            enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "{{ .Values.spec.namespace }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
